# Generated by Django 4.0.3 on 2022-04-04 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('WORKER', 'Рабочий'), ('MANAGER', 'Управляющий')], default='WORKER', max_length=100, verbose_name='Статус пользователя')),
                ('full_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Полное имя')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='Доступен для работы')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновления')),
                ('test_user', models.BooleanField(default=False, verbose_name='Тестовый пользователь')),
                ('show_all_works', models.BooleanField(default=False, verbose_name='Показывать все вакансии')),
                ('mobile_os', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Пользовательская ОС')),
                ('mobile_model', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ИМя пользователя (логин)')),
            ],
        ),
    ]
