# Generated by Django 3.2.13 on 2022-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Фамилия'),
        ),
    ]
