# Generated by Django 4.0.3 on 2022-04-04 06:02

import core.custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя')),
                ('userfullname', core.custom.fields.CharFieldStripped(max_length=64, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('password', core.custom.fields.CharFieldStripped(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Запрос на регистрацию',
                'verbose_name_plural': 'Запросы на регистрацию',
            },
        ),
    ]
