# Generated by Django 3.2.13 on 2022-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='userfullname',
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='second_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия'),
        ),
    ]
