# Generated by Django 3.2.13 on 2022-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20220511_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='done',
            field=models.BooleanField(default=True, verbose_name='Работа выполнена?'),
        ),
    ]
