# Generated by Django 3.2.13 on 2022-05-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_workmodel_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmodel',
            name='execution',
        ),
    ]
