# Generated by Django 3.2.13 on 2022-05-24 16:42

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_modelnotes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnotes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.generate_upload_name, verbose_name='Фотографии объекта'),
        ),
    ]
