# Generated by Django 3.2.13 on 2022-05-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_remove_workmodel_execution'),
        ('notes', '0003_alter_modelnotes_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnotes',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_notes', to='work.workmodel', verbose_name='Работа'),
        ),
    ]
