# Generated by Django 3.2.13 on 2022-05-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djeym', '0002_auto_20220504_1940'),
        ('notes', '0004_modelnotes_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnotes',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marker_notes', to='djeym.placemark', verbose_name='Маркер на карте'),
        ),
    ]
